repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=100]
        feat/winappdriver-integration
        language_version: python3.12
        language_version: python3.11
